# Generated by Django 3.1.3 on 2022-05-06 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0067_auto_20220407_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='celltype',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
