# Generated by Django 3.1.3 on 2022-05-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0068_celltype_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='celltype',
            name='is_most_recent',
            field=models.BooleanField(default=False),
        ),
    ]
